name: Testes E2E

on:
  push:
    branches:
      - main

jobs:
  testes_e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci

    - name: Install Cypress
      run: npm install -g cypress

    - name: Run Cypress Tests
      run: npx cypress run
