name: CI

on:
  push:
    branches:
      - main

jobs:
  testes_e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npm install -g cypress

      - name: Create Videos Directory
        run: mkdir -p cypress/videos

      - name: Run Cypress Tests
        run: npx cypress run --record --key 5dd06092-8d4b-437d-a290-778699fecdd1 --config videosFolder=cypress/videos

  k6:
    needs: testes_e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run K6 load test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: testeDeCarga/teste.js
